version: 2
jobs:
    build:
        docker:
            - image: microsoft/dotnet:2.1-sdk-alpine
        steps:
            - checkout
            - run:
                    name: Restore Packages
                    command: dotnet restore --no-cache --force --verbosity normal
            - run:
                    name: Build
                    command: dotnet build --no-restore --no-incremental --verbosity normal --configuration Release
            - run:
                    name: Run Tests
                    command: dotnet test --no-restore --no-build --verbosity normal --configuration Release PrimeService.Tests
            - run:
                    name: Packaging
                    command: dotnet pack --no-restore --no-build --verbosity normal --configuration Release --output "..\output\packages\"
            - store_artifacts:
                path: output/packages/